services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: notesdb_test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test

  backend-test:
    build:
      context: ./backend
      dockerfile: Dockerfile.test
    environment:
      POSTGRES_DB: notesdb_test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      - db
