services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: notesdb
      POSTGRES_USER: notes
      POSTGRES_PASSWORD: notes
    ports:
      - "5434:5432"  # Prod DB Host-Port
    volumes:
      - db_prod_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    environment:
      POSTGRES_DB: notesdb
      POSTGRES_USER: notes
      POSTGRES_PASSWORD: notes
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      NODE_ENV: production
    ports:
      - "8002:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:8002
    ports:
      - "5175:80"
    depends_on:
      - backend

volumes:
  db_prod_data:
