name: Mini-Notes CI/CD

on:
  push:
    branches:
      - main
      - dev
      - test

env:
  REGISTRY: ghcr.io
  IMAGE_BACKEND: mini-notes-backend
  IMAGE_FRONTEND: mini-notes-frontend

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set environment
        id: env
        run: |
          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            echo "ENV=prod" >> $GITHUB_ENV
            echo "TAG=prod" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF##*/}" == "dev" ]]; then
            echo "ENV=dev" >> $GITHUB_ENV
            echo "TAG=dev" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF##*/}" == "test" ]]; then
            echo "ENV=test" >> $GITHUB_ENV
            echo "TAG=test" >> $GITHUB_ENV

      - name: Build & Push Backend
        run: |
          docker build -t $REGISTRY/${{ github.repository_owner }}/$IMAGE_BACKEND:${{ env.TAG }} ./backend
          docker push $REGISTRY/${{ github.repository_owner }}/$IMAGE_BACKEND:${{ env.TAG }}

      - name: Build & Push Frontend
        run: |
          docker build -t $REGISTRY/${{ github.repository_owner }}/$IMAGE_FRONTEND:${{ env.TAG }} ./frontend
          docker push $REGISTRY/${{ github.repository_owner }}/$IMAGE_FRONTEND:${{ env.TAG }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/test'
    steps:
      - name: SSH Deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/mini-notes-app
            docker-compose -f docker-compose.${{ env.ENV }}.yml pull
            docker-compose -f docker-compose.${{ env.ENV }}.yml up -d --remove-orphans
