name: CI

on:
  push:
    branches: [dev, main]

env:
  REGISTRY: ghcr.io
  BACKEND_IMAGE: sasha1902/mini-notes-backend
  FRONTEND_IMAGE: sasha1902/mini-notes-frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set tag
        id: tag
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "TAG=prod" >> $GITHUB_OUTPUT
          else
            echo "TAG=test" >> $GITHUB_OUTPUT
          fi

      - name: Build & push backend
        run: |
          docker build -t ghcr.io/${{ env.BACKEND_IMAGE }}:${{ steps.tag.outputs.TAG }} ./backend
          docker push ghcr.io/${{ env.BACKEND_IMAGE }}:${{ steps.tag.outputs.TAG }}

      - name: Build & push frontend
        run: |
          docker build -t ghcr.io/${{ env.FRONTEND_IMAGE }}:${{ steps.tag.outputs.TAG }} ./frontend
          docker push ghcr.io/${{ env.FRONTEND_IMAGE }}:${{ steps.tag.outputs.TAG }}
